spring:
  application:
    name: spock20-demo
  main:
    banner-mode: off
  profiles:
    active: dev

logging:
  level:
    org.apache.tomcat: warn
    org.apache.catalina: warn
    org.apache.coyote: warn
    org.springframework: warn
