# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run Tests with Groovy 2.5.15, Spock 1.3
          command: mvn clean verify -Dspock.version=1.3-groovy-2.5 -Dgroovy.version=2.5.15 -Dsurefire.reportNameSuffix=1.3-2.5

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/1.3-2.5

      - run:
          name: Run Tests with Groovy 2.5.15, Spock 2.0
          command: mvn clean verify -Dspock.version=2.0-groovy-2.5 -Dgroovy.version=2.5.15 -Dsurefire.reportNameSuffix=2.0-2.5

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/2.0-2.5

      - run:
          name: Run Tests with Groovy 3.0.9, Spock 2.0
          command: mvn clean verify -Dspock.version=2.0-groovy-3.0 -Dgroovy.version=3.0.9 -Dsurefire.reportNameSuffix=2.0-3.0

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/2.0-3.0

      - run:
          name: Run Tests with Groovy 3.0.9, Spock 2.1
          command: mvn clean verify -Dspock.version=2.1-groovy-3.0 -Dgroovy.version=3.0.9 -Dsurefire.reportNameSuffix=2.0-3.0

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/2.1-3.0

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
