# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/developer/ja/images/image/cimg/openjdk
      - image: cimg/openjdk:17.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run Tests with Groovy 3.0.14, Spock 2.3
          command: mvn clean verify -Dspock.version=2.3-groovy-3.0 -Dgroovy.version=3.0.14 -Dsurefire.reportNameSuffix=2.3-3.0

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/2.3-3.0

      - run:
          name: Run Tests with Groovy 3.0.14, Spock 2.4
          command: mvn clean verify -Dspock.version=2.4-M1-groovy-3.0 -Dgroovy.version=3.0.14 -Dsurefire.reportNameSuffix=2.3-3.0

      - store_test_results:
          path: ./target/surefire-reports
      - store_artifacts:
          path: ./target/surefire-reports
          destination: artifacts/2.4-3.0

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
